name: knip
on:
  pull_request:

permissions:
  checks: write
  issues: write
  pull-requests: write

jobs:
  knip:
    steps:
      - name: Post the knip results
        uses: codex-/knip-reporter@v2

